version: "v1"

http:
  port: 3000
  host: "0.0.0.0"

db:
  host: localhost
  port: 7001
  user: call-center
  password: call-center
  db: postgres
  ssl_mode: disable

grpc:
  host: localhost
  port: 44044
